In [46]:
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_html("https://fbref.com/es/comps/12/shooting/Estadisticas-de-La-Liga", encoding='UTF-8')

In [47]:
data=data[0]

In [50]:
pd.concat([data['Unnamed: 0_level_0'],data['Estándar']],axis=1).sort_values(by='Gls.').reset_index(drop=True)

,Equipo,Gls.,Dis,DaP,% de TT,T/90,TalArc/90,G/T,G/TalArc,Dist,FK,TP,TPint
0,Cádiz,15,195,58,29.7,9.29,2.76,0.07,0.22,18.4,14,2,2
1,Alavés,16,265,72,27.2,12.62,3.43,0.05,0.19,17.6,11,2,4
2,Rayo Vallecano,18,253,92,36.4,12.65,4.60,0.05,0.14,20.6,24,5,5
3,Mallorca,19,229,69,30.1,10.90,3.29,0.08,0.26,17.0,3,1,3
4,Celta Vigo,20,274,80,29.2,13.05,3.81,0.07,0.24,18.0,12,1,3
5,Granada,20,219,75,34.2,10.43,3.57,0.08,0.23,16.8,8,3,4
6,Almería,21,262,86,32.8,12.48,4.10,0.08,0.23,18.4,11,1,1
7,Las Palmas,21,207,65,31.4,9.86,3.10,0.09,0.28,20.9,11,3,4
8,Sevilla,24,313,94,30.0,14.90,4.48,0.07,0.24,18.0,12,1,1
9,Betis,24,291,83,28.5,13.86,3.95,0.08,0.29,16.7,6,0,0
10,Osasuna,25,228,71,31.1,11.40,3.55,0.09,0.30,17.7,7,4,4
11,Getafe,26,229,84,36.7,11.45,4.20,0.09,0.25,17.9,2,5,5
12,Valencia,27,197,69,35.0,9.38,3.29,0.12,0.33,18.7,12,4,4
13,Villarreal,28,237,83,35.0,11.29,3.95,0.10,0.29,15.8,5,4,4
14,Real Sociedad,30,249,81,32.5,11.86,3.86,0.11,0.33,17.8,15,3,3
15,Athletic Club,37,282,105,37.2,13.43,5.00,0.12,0.32,15.2,3,3,5
16,Barcelona,38,328,122,37.2,16.40,6.10,0.11,0.29,16.1,11,3,3
17,Atlético Madrid,40,248,105,42.3,12.40,5.25,0.15,0.35,15.5,5,3,3
18,Real Madrid,43,331,122,36.9,16.55,6.10,0.13,0.34,17.7,16,1,3
19,Girona,51,268,101,37.7,12.76,4.81,0.18,0.48,16.4,5,3,3